### PR TITLE
Bump dynamic sdk version

### PR DESCRIPTION
**Pull request by david-martin**
Allows for later version of [ResourceYamlEditor](https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/docs/api.md#resourceyamleditor) props

### CODE REVIEW

**Review by jasonmadigan — APPROVED** [review]
LGTM

**Comment by jasonmadigan** [comment]
actually, I think this may have broken npm (I don't know why the plugin examples and console uses both yarn and npm, but anyway) + webpack.

**Comment by david-martin** [comment]
> actually, I think this may have broken npm (I don't know why the plugin examples and console uses both yarn and npm, but anyway) + webpack.

@jasonmadigan consolidate on yarn?

**Comment by jasonmadigan** [comment]
Think a downgrade of babel-loader will fixup. Il'l send a PR on.

**Comment by jasonmadigan** [comment]
Fixed via https://github.com/Kuadrant/console-plugin/pull/57

**Pull request merged**
